/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assets from "./assets";
export type { assets };
import type * as uniswapV2 from "./uniswapV2";
export type { uniswapV2 };
export type { Adapter } from "./Adapter";
